DESCRIPTION = "Telechips T-Util"
SECTION = "T-Util"
LICENSE = "Telechips"
LIC_FILES_CHKSUM = "file://${THISDIR}/../../licenses/Telechips;md5=bf748a8e7a397a71f48f21715741f8a1"


inherit cmake pkgconfig

DEPENDS = "glib-2.0"

SRC_URI = "${TELECHIPS_TOPST_GIT}/t-util.git;protocol=${TOPST_GIT_PROTOCOL};branch=${TOPST_BRANCH}"
SRCREV = "6cac60f46916aed51320f7a60c19a4775276cf5f"

S = "${WORKDIR}/git"
B = "${S}"

PATCHTOOL = "git"
#PACKAGE_ARCH = "${MACHINE_ARCH}"


EXTRA_OECMAKE += "-DLINUX_KERNEL_DIR=${STAGING_KERNEL_DIR}"
EXTRA_OECMAKE += "-DCHIPSET=${TCC_ARCH_FAMILY}"
EXTRA_OECMAKE += "-DCHIPSET_CORE=${TCC_MACHINE_FAMILY}"
EXTRA_OECMAKE += "-DLINUX_KERNEL_VERSION=${LINUX_VERSION}"


FILES:${PN} += " \
	${libdir}/*.so \
"

FILES_SOLIBSDEV = ""
INSANE_SKIP:${PN} += "dev-so"
