# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory containing .bb and .bbappend files, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
			${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "telechips-topst"
BBFILE_PATTERN_telechips-topst = "^${LAYERDIR}/"
BBFILE_PRIORITY_telechips-topst = "11"

BBFILES_DYNAMIC += " \
    selinux:${LAYERDIR}/dynamic-layers/meta-selinux/*/*/*.bbappend \
    flutter-layer:${LAYERDIR}/dynamic-layers/meta-flutter/*/*/*.bb \
    flutter-layer:${LAYERDIR}/dynamic-layers/meta-flutter/*/*/*.bbappend \
    xfce-layer:${LAYERDIR}/dynamic-layers/meta-xfce/*/*/*.bbappend \
    chromium-browser-layer:${LAYERDIR}/dynamic-layers/meta-chromium/*/*/*.bbappend \
    firefox-browser-layer:${LAYERDIR}/dynamic-layers/meta-firefox/*/*/*.bbappend \
    gnome-layer:${LAYERDIR}/dynamic-layers/meta-gnome/*/*/*.bbappend \
    networking-layer:${LAYERDIR}/dynamic-layers/meta-networking/*/*/*.bbappend \
"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_telechips-topst = "2"
LAYERDEPENDS_telechips-topst = "telechips-topst-bsp"
LAYERSERIES_COMPAT_telechips-topst = "kirkstone"

LICENSE_PATH += "${LAYERDIR}/licenses"

# Exclude recipes from being cleared by rm_work
RM_WORK_EXCLUDE += " \
		topst-nano-server topst-welcome libtcndnpu tc-compiled-nn tc-nn-app tc-nn-camera-app visionprotocol \
		telechips-topst-image-minimal telechips-topst-image-multimedia telechips-topst-image telechips-topst-subcore-image\
		meta-toolchain-telechips-topst customize-rootfs \
"

CORE_IMAGE_EXTRA_INSTALL:append = "${@bb.utils.contains('TOPST_FEAUTES', 'bootchart', ' systemd-bootchart systemd-analyze', '', d)}"
EXTRA_CMDLINE:append = "${@bb.utils.contains('TOPST_FEATURES', 'bootchart', ' bootchart printk.time=1 initcall_debug', '', d)}"
